[package]
name = "magmakit"
version = "0.1.0"
authors = ["wareya <wareya@gmail.com>"]
edition = "2018"

[dependencies]
image = "*"
glium = "0.25.1"
glyph_brush = "*"
gammakit = { path = "../gammakit" }
